---
- name: "LAMP setup in Redhat servers"
  hosts: Redhat
  become: true
  vars:
    httpd_owner: apache
    httpd_group: apache
  tasks:
    
    - name: "installing apache,mariadb and php"
      yum:
         name:
            - httpd
            - mariadb-server
            - php
            - php-mysql
         state: present

    - name: "set phpinfo page"
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/index.php
        owner: "{{httpd_owner}}"
        group: "{{httpd_group }}"

    - name: "restarting and enabling httpd and mysql"
      service: 
        name: "{{item}}"
        state: restarted
        enabled: true
      with_items:
        - httpd
        - mariadb
